package com.atarion.game.entidad.jugador;

public enum Direccion 
{
    PARADO,
    ARRIBA,ABAJO,DERECHA,IZQUIERDA,
    LATERAL_DERECHO_ARRIBA,LATERAL_DERECHO_ABAJO,LATERAL_IZQUIERDO_ARRIBA,LATERAL_IZQUIERDO_ABAJO
}
